from PySide2.QtCore import QCoreApplication, QMetaObject, QRect, QSize, Qt
from PySide2.QtGui import QCursor, QFont

from PySide2.QtWidgets import (QLabel, QRadioButton,
                               QPushButton, QPlainTextEdit, QDial)


class Ui_Form(object):
    def setupUi(self, Form):
        if Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(799, 600)
        self.dial = QDial(Form)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(600, 160, 101, 81))
        self.dial.setMouseTracking(False)
        self.dial.setTabletTracking(False)
        self.dial.setMaximum(240)
        self.dial.setTracking(True)
        self.label_wheel = QLabel(Form)
        self.label_wheel.setObjectName(u"label_wheel")
        self.label_wheel.setGeometry(QRect(536, 82, 231, 241))
        self.label_wheel.setCursor(QCursor(Qt.UpArrowCursor))
        self.label_wheel.setScaledContents(True)
        self.label_wheel.setAlignment(
            Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.label_round_number = QLabel(Form)
        self.label_round_number.setObjectName(u"label_round_number")
        self.label_round_number.setGeometry(QRect(300, 10, 183, 55))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(36)
        self.label_round_number.setFont(font)
        self.label_name1 = QLabel(Form)
        self.label_name1.setObjectName(u"label_name1")
        self.label_name1.setGeometry(QRect(50, 370, 155, 41))
        font1 = QFont()
        font1.setFamily(u"Arial Black")
        font1.setPointSize(22)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_name1.setFont(font1)
        self.label_name1.setScaledContents(True)
        self.label_name1.setAlignment(Qt.AlignCenter)
        self.label_name2 = QLabel(Form)
        self.label_name2.setObjectName(u"label_name2")
        self.label_name2.setGeometry(QRect(320, 370, 155, 41))
        self.label_name2.setFont(font1)
        self.label_name2.setScaledContents(True)
        self.label_name2.setAlignment(Qt.AlignCenter)
        self.label_name3 = QLabel(Form)
        self.label_name3.setObjectName(u"label_name3")
        self.label_name3.setGeometry(QRect(580, 370, 155, 41))
        self.label_name3.setFont(font1)
        self.label_name3.setScaledContents(True)
        self.label_name3.setAlignment(Qt.AlignCenter)
        self.label_points1 = QLabel(Form)
        self.label_points1.setObjectName(u"label_points1")
        self.label_points1.setGeometry(QRect(53, 430, 141, 33))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setPointSize(22)
        self.label_points1.setFont(font2)
        self.label_points1.setScaledContents(True)
        self.label_points1.setAlignment(Qt.AlignCenter)
        self.label_points2 = QLabel(Form)
        self.label_points2.setObjectName(u"label_points2")
        self.label_points2.setGeometry(QRect(330, 420, 131, 33))
        self.label_points2.setFont(font2)
        self.label_points2.setScaledContents(True)
        self.label_points2.setAlignment(Qt.AlignCenter)
        self.label_points3 = QLabel(Form)
        self.label_points3.setObjectName(u"label_points3")
        self.label_points3.setGeometry(QRect(590, 420, 131, 33))
        self.label_points3.setFont(font2)
        self.label_points3.setScaledContents(True)
        self.label_points3.setAlignment(Qt.AlignCenter)
        self.label_word = QLabel(Form)
        self.label_word.setObjectName(u"label_word")
        self.label_word.setGeometry(QRect(20, 160, 311, 161))
        self.label_word.setFont(font1)
        self.label_word.setAlignment(
            Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
        self.radioButton_player1 = QRadioButton(Form)
        self.radioButton_player1.setObjectName(u"radioButton_player1")
        self.radioButton_player1.setEnabled(False)
        self.radioButton_player1.setGeometry(QRect(120, 320, 171, 81))
        font3 = QFont()
        font3.setPointSize(14)
        self.radioButton_player1.setFont(font3)
        self.radioButton_player1.setIconSize(QSize(36, 36))
        self.radioButton_player1.setCheckable(True)
        self.radioButton_player1.setChecked(True)
        self.radioButton_player2 = QRadioButton(Form)
        self.radioButton_player2.setObjectName(u"radioButton_player2")
        self.radioButton_player2.setEnabled(False)
        self.radioButton_player2.setGeometry(QRect(390, 330, 91, 61))
        self.radioButton_player2.setIconSize(QSize(36, 36))
        self.radioButton_player2.setCheckable(True)
        self.radioButton_player2.setChecked(False)
        self.radioButton_player3 = QRadioButton(Form)
        self.radioButton_player3.setObjectName(u"radioButton_player3")
        self.radioButton_player3.setEnabled(False)
        self.radioButton_player3.setGeometry(QRect(651, 350, 81, 21))
        self.radioButton_player3.setIconSize(QSize(36, 36))
        self.roll_the_wheel_button = QPushButton(Form)
        self.roll_the_wheel_button.setObjectName(u"roll_the_wheel_button")
        self.roll_the_wheel_button.setGeometry(QRect(560, 0, 191, 41))
        font4 = QFont()
        font4.setFamily(u"Arial Black")
        font4.setPointSize(18)
        font4.setBold(True)
        font4.setWeight(75)
        self.roll_the_wheel_button.setFont(font4)
        self.answerButton = QPushButton(Form)
        self.answerButton.setObjectName(u"answerButton")
        self.answerButton.setGeometry(QRect(320, 490, 164, 35))
        font5 = QFont()
        font5.setFamily(u"Arial Black")
        font5.setPointSize(14)
        font5.setBold(True)
        font5.setWeight(75)
        self.answerButton.setFont(font5)
        self.vowelButton = QPushButton(Form)
        self.vowelButton.setObjectName(u"vowelButton")
        self.vowelButton.setGeometry(QRect(580, 490, 183, 35))
        self.vowelButton.setFont(font5)
        self.ConsonantButton = QPushButton(Form)
        self.ConsonantButton.setObjectName(u"ConsonantButton")
        self.ConsonantButton.setGeometry(QRect(20, 490, 220, 35))
        self.ConsonantButton.setFont(font5)
        self.label_wheel_worth = QLabel(Form)
        self.label_wheel_worth.setObjectName(u"label_wheel_worth")
        self.label_wheel_worth.setGeometry(QRect(560, 50, 191, 21))
        font6 = QFont()
        font6.setPointSize(16)
        self.label_wheel_worth.setFont(font6)
        self.label_wheel_worth.setAlignment(Qt.AlignCenter)
        self.label_category = QLabel(Form)
        self.label_category.setObjectName(u"label_category")
        self.label_category.setGeometry(QRect(20, 60, 281, 81))
        self.label_category.setFont(font4)
        self.answerTextEdit = QPlainTextEdit(Form)
        self.answerTextEdit.setObjectName(u"answerTextEdit")
        self.answerTextEdit.setGeometry(QRect(230, 540, 331, 31))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_wheel.setText("")
        self.label_round_number.setText(
            QCoreApplication.translate("Form", u"Runda 1", None))
        self.label_name1.setText(
            QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_name2.setText(
            QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_name3.setText(
            QCoreApplication.translate("Form", u"TextLabel", None))
        self.label_points1.setText(
            QCoreApplication.translate("Form", u"0", None))
        self.label_points2.setText(
            QCoreApplication.translate("Form", u"0", None))
        self.label_points3.setText(
            QCoreApplication.translate("Form", u"0", None))
        self.label_word.setText(QCoreApplication.translate(
            "Form", u"TextLabel", None))
        self.radioButton_player1.setText("")
        self.radioButton_player2.setText("")
        self.radioButton_player3.setText("")
        self.roll_the_wheel_button.setText(QCoreApplication.translate(
            "Form", u"Zakr\u0119\u0107 Ko\u0142em", None))
        self.answerButton.setText(QCoreApplication.translate(
            "Form", u"Odgadnij has\u0142o", None))
        self.vowelButton.setText(QCoreApplication.translate(
            "Form", u"Kup samog\u0142osk\u0119", None))
        self.ConsonantButton.setText(QCoreApplication.translate(
            "Form", u"Odgadnij sp\u00f3\u0142g\u0142osk\u0119", None))
        self.label_wheel_worth.setText(QCoreApplication.translate(
            "Form", u"", None))
        self.label_category.setText(QCoreApplication.translate(
            "Form", u"Kategoria: ", None))
    # retranslateUi
